metadata:
    name: spark-pipeline
sparkApp:
  spec:
    type: Java
    image: "docker-registry-PLACEHOLDER/repository/final-561-spark-worker-docker:1.0.0-SNAPSHOT"
    mainClass: org.test.SparkPipelineDriver
    mainApplicationFile: "local:///opt/spark/jobs/pipelines/spark-pipeline.jar"
    deps:
      packages:
        - mysql:mysql-connector-java:8.0.30
        - org.apache.hadoop:hadoop-aws:3.4.1
        - software.amazon.awssdk:bundle:2.25.53
      excludePackages: []
    hadoopConf:
      fs.s3a.fast.upload: "true"
      fs.s3a.path.style: "true"
    driver:
      cores: 1
      coreLimit: "1200m"
      memory: "2048m"
      # Setup these secret key references within your SealedSecret 
      envFrom:
        - secretRef:
            name: remote-auth-config
      env:
        - name: KRAUSENING_BASE
          value: /opt/spark/krausening/base
      javaOptions: "-DKRAUSENING_BASE=/opt/spark/krausening/base"
    executor:
      cores: 1
      memory: "4096m"
      envFrom:
        - secretRef:
            name: remote-auth-config
      env:
        - name: KRAUSENING_BASE
          value: /opt/spark/krausening/base
      javaOptions: "-DKRAUSENING_BASE=/opt/spark/krausening/base"
